namespace: homelab
name: common_roles
version: '1.0.0'
description: Ansible roles that are shared across project specific roles.
repository: https://github.com/Johnny-Knighten/ansible-homelab-common-roles
authors:
  - Johnny Knighten
readme: README.md
tags:
  - linx
  - tools
